### PR TITLE
Prevent crash when log file is misconfigured

### PR DESCRIPTION
**Pull request by jhrcek**
This is my attemp at fixing https://github.com/haskell/haskell-language-server/issues/452
by falling back to stderr loggin in cases when the attempt to open the log file fails.

### CODE REVIEW

**Comment by Anrock** [comment]
IMO, expected behaviour would be to create log file. It's not like I manually create logfiles for all the software on my pc :thinking:

**Comment by jhrcek** [comment]
Well, `openFile filePath AppendMode` DOES create the file, IF the directory which you provide exists.

But it
1. doesn't deal with stuff like `~` 
2. doesn't create directories on the path to file.

But if you think it's the right approach, I could extend this PR to [createDirectoryIfMissing](https://hackage.haskell.org/package/directory-1.3.6.1/docs/System-Directory.html#v:createDirectoryIfMissing) which fixes problem 2., but it doesn't help with 1.

**Comment by bubba** [comment]
This makes sense to me, thanks! If its not too much trouble could you make this PR against wz1000:singleton-methods [here](https://github.com/alanz/haskell-lsp/pulls)? We're going to merge it soon and it would be nice to avoid the merge conflicts

**Comment by Anrock** [comment]
@jhrcek sorry, my bad. I didn't realize that `AppendMode` also creates file if it doesn't exist.

**Comment by jhrcek** [comment]
@bubba sure, opened here https://github.com/wz1000/haskell-lsp/pull/3

**Comment by bubba** [comment]
Thanks, this should make it into the 1.0.0.0 release then

**Pull request closed without merging**
