### PR TITLE
add support for Selection Range requests

### LINKED ISSUE #254: Support Selection Range
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_selectionRange

### PR DESCRIPTION
**Pull request by grepcake**
closes #254

### CODE REVIEW

**Comment by grepcake** [comment]
Unfortunately, I didn't notice it at first, buty my global haskell-stylish setup has brought in many unrelated cosmetic changes. Please, tell, if I should remove them.

**Comment by grepcake** [comment]
Oh, it's already been done in https://github.com/alanz/haskell-lsp/pull/244. How embarrassing.

**Comment by wz1000** [comment]
Yeah, I would encourage you to use that branch. It pretty much complete now, except we are working on patches for downstream users (ghcide, hls) before merging.

If you want this to be merged into the current version of haskell-lsp, please remove the formatting changes in order to not make the rebase a pain.

**Comment by grepcake** [comment]
I think it's okay, if it's almost ready, I'll use the other branch.

**Pull request closed without merging**
