### PR TITLE
Add withProgress and wiithIndefiniteProgress

### LINKED ISSUE #144: Add support for window/progress
https://github.com/Microsoft/vscode-languageserver-node/pull/261

Vscode and sourcegraph clients implement this at least.

### PR DESCRIPTION
**Pull request by bubba**
Closes #144

### CODE REVIEW

**Comment by bubba** [comment]
Demo of `withIndefiniteProgress` being used in HIE
Screen Recording 2019-04-22 at 03 08 09

**Comment by alanz** [comment]
Looks good.

BTW, what plugin are you using for github integration?

**Comment by bubba** [comment]
@alanz the GitHub plugin! It’s handy for doing code reviews, it lets you check out PRs really easily

**Comment by mpickering** [comment]
This PR introduced trailing whitespace into the code base. Please can you configure your editor @bubba to strip whitespace when you save?

**Comment by bubba** [comment]
@mpickering Found the setting in VS code under `Files: Trim Trailing Whitespace` for anyone else looking for it

**Pull request merged**
