### PR TITLE
Make sure to escape URIs properly for Windows file paths

### LINKED ISSUE #75: URLs are not correctly encoded when publishing diagnostics
[The spec](https://microsoft.github.io/language-server-protocol/specification#basic-json-structures) says that URIs should be encoded according to RFC3986; incoming URIs are decoded in `uriToFilePath` but not encoded in `filePathToUri`.

(I am working on fixing this!)

See also: [vscode-hie-server #47](https://github.com/alanz/vscode-hie-server/issues/47)

### PR DESCRIPTION
**Pull request by johnsonwj**
Fixes #75. Also added a couple of pretty dumb tests!

### CODE REVIEW

**Comment by wz1000** [comment]
Looks good. Could you enable CircleCI for your fork?

This might also be of some interest: https://github.com/ekmett/coda/blob/master/lib/coda-lsp/Language/Server/Protocol.hs#L489

**Comment by johnsonwj** [comment]
Sweet, circleci is enabled!

It looks like `coda-lsp` has the same problem...I will look into putting in a PR there too!

**Comment by johnsonwj** [comment]
PS - I am trying to verify that this is in fact the root cause of [vscode-hie-server #47](https://github.com/alanz/vscode-hie-server/issues/47), but I am having trouble getting VS Code to run HIE with my local build of `haskell-lsp`. So that is pending. 

PPS - given that this filepath <--> URI issue appears in more than one place, would this be a good candidate for a hackage library or will copypasting to `coda-lsp` be sufficient?

**Comment by alanz** [comment]
@johnsonwj if you want to make a library it will help the community.

But in the mean time I am going to merge this. Thanks.

**Pull request merged**
